---
title: hugocarreira - person blog
email: hugo.colombo23@gmail.com
author: hugocarreira
author_github: Hugo Carreira
description: |
  apenas o meu blog! :)
baseurl: "/"
permalink: :title
url: http://hugocarreira.github.io
paginate: 12
github:
  user: hugocarreira
  repository: my-blog
  url: http://hugocarreira.github.io/
  status: false
home_bgfile: bg2.jpg
sass:
  sass_dir: assets/css
  style: compressed
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
- jekyll-paginate
- jekyll-paginate
- jekyll-sass-converter
- sass
- jekyll-seo-tag
exclude:
- vendor
